services: 
  spring:
    build: ./backend
    container_name: olib-spring
    ports:
      - "8080:8080"
    depends_on:
      - olib-database
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /usr/src/backend
          ignore:
            - .idea
            - .mvn
            - target
    networks:
      - backend

  olib-database:
    image: 'postgres:latest'
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    container_name: olib-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database/db-data/:/var/lib/postgresql/data/

networks:
  backend:
    driver: host
