services: 
  olib-spring:
    build: ./backend
    container_name: olib-spring
    ports:
      - "8080:8080"
    depends_on:
      olib-database:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /usr/src/backend
          ignore:
            - .idea
            - .mvn
            - target
    volumes:
      - ./backend:/usr/src/backend
      - ./backend/target:/usr/src/backend/target

  olib-database:
    image: 'postgres:latest'
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    container_name: olib-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database/db-data/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s

  olib-frontend:
    build: ./frontend
    container_name: olib-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    depends_on:
      - olib-database
      - olib-spring
